name: CI
run-name: Running CI for ${{ github.head_ref }}

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]

permissions:
  checks: write
  actions: write
  contents: write
  packages: write
  statuses: write
  pull-requests: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: 'Australia/Sydney'
  LANG: 'en_AU.UTF-8'

jobs:
  pr-name-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --legacy-peer-deps
      - name: 'Checking PR Naming Convention'
        continue-on-error: false
        shell: bash
        run: echo "${{ github.event.pull_request.title }}" | commitlint
        # gh pr comment ${{ github.event.pull_request.number }} --body "$body_comment"
        # run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
        env:
          GITHUB_TOKEN: ${{ github.token }}

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: github/codeql-action/init@v2
        with:
          languages: javascript
          config-file: ./.github/codeql/codeql-config.yml
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: critical
          license-check: true
          vulnerability-check: false

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --legacy-peer-deps
      - run: npm run typecheck

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --legacy-peer-deps
      - run: npm run codestyle

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --legacy-peer-deps
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --legacy-peer-deps
      - run: npm run test:ci
